# Question 4 

For this question of predictig the category class for the items:
1. We have training Data under Data/train.csv and testing data under Data/test.csv
2. The the variables(columns from the data) are < item_id, sold_price, price, area_name, condition, size, listing_at, item_tag_hash > and the dependent variable is < category_class >

In [137]:
import pandas as pd
import numpy as np
import os

from sklearn.preprocessing import LabelBinarizer
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.metrics import precision_recall_fscore_support as prfs
from sklearn.metrics import f1_score, make_scorer 

from sklearn.naive_bayes import MultinomialNB  # Multinomial Naive Bayes
from sklearn.linear_model import LogisticRegression # Logistic Regression
from sklearn.ensemble import RandomForestClassifier #Random Forest
from sklearn.tree import DecisionTreeClassifier # Decision Tree 

In [89]:
current_path = os.getcwd()
# print(os.getcwd())

In [90]:
master_Train_Data = current_path + '/Data/train.csv'
master_Test_Data = current_path + '/Data/test.csv'

In [97]:
data = pd.read_csv(master_Train_Data, encoding='utf-8')
data.head()

item_id  category_class  sold_price  price area_name condition  size  \
0     7966             0.0        1164   1162       fff      Fair     7   
1     1850             0.0        1005   1004       fff      Fair     3   
2     7582             2.0         944    944       aaa      Fair     5   
3     6560             0.0        1068   1067       fff      Fair     7   
4     7368             3.0        1407   1407       ddd      Good    15   

                   listing_at                             item_tag_hash  
0  2017-02-01 16:11:18.978516  3ca192bd7558780793444f73366c58d60c9d7775  
1  2017-02-02 14:42:51.693295  fbaacb960902382e4f6c96f2d8f225c24eecadb4  
2  2017-02-03 01:55:53.406374  785a7925363bf133a7c5413c563f331c5e02cc69  
3  2017-01-30 23:34:02.268603  f8997252c6e5ae3d950b736e1a81160a2e937a7f  
4  2017-02-03 13:38:37.845010  ca59bcd3da4daac52f3fcfdc0ab963f65cf421bc

In [98]:
# converting datetime to individual values
data['listing_at'] = pd.to_datetime(data['listing_at'], format='%Y-%m-%d %H:%M:%S.%f')
data['month'] = data['listing_at'].dt.month
data['year'] = data['listing_at'].dt.year
data['day'] = data['listing_at'].dt.day
data['minute'] = data['listing_at'].dt.minute
data['hour'] = data['listing_at'].dt.hour
data['weekday'] = data['listing_at'].dt.weekday
# converting category_class to ints
data['category_class'] = data.category_class.astype(int)
data

item_id  category_class  sold_price  price area_name condition  size  \
0       7966               0        1164   1162       fff      Fair     7   
1       1850               0        1005   1004       fff      Fair     3   
2       7582               2         944    944       aaa      Fair     5   
3       6560               0        1068   1067       fff      Fair     7   
4       7368               3        1407   1407       ddd      Good    15   
5       9404               2         980    979       ddd      Good     3   
6       8367               1        1371   2102       jjj      Good    11   
7       7710               2         771    770       hhh      Good     2   
8       5402               0        1004   1003       fff  Like New     2   
9       1909               4        1096   1095       bbb      Good     3   
10      2791               4         971    970       aaa  Like New     4   
11      7451               0        1160   1157       hhh      Good     3   
12      6184               1        1332   1329       ccc      Good    26   
13      2327               2        1077   1077       ggg  Like New     6   
14      4990               0        1094   1091       fff      Fair     7   
15      8635               0         889    888       kkk      Fair     7   
16      3273               1        1154   1151       kkk      Fair     9   
17      6054               0         877    877       ddd      Good     4   
18      8212               2        1188   1186       ccc  Like New    14   
19      9175               2         858    856       ddd      Fair     7   
20      6034               0        1159   1157       ccc      Fair    14   
21      5531               3        1424   1423       kkk      Good     9   
22      3987               0        1187   1187       bbb      Good    13   
23      2193               0         876    876       fff      Fair     2   
24      5804               2        1058   1056       aaa      Good    10   
25      4562               0        1221   1220       aaa  Like New    12   
26      2966               2         933    930       jjj      Fair     5   
27      3084               0        1046   1046       kkk      Good     3   
28      6428               0        1062   1062       ggg      Fair    18   
29      7388               0        1101   1102       eee  Like New     3   
..       ...             ...         ...    ...       ...       ...   ...   
670     6604               4         870    868       eee      Good     4   
671     9262               3        1272   1271       bbb      Good    20   
672     1587               3        1267   1267       ccc      Good    31   
673     4718               0         974    974       eee      Good     3   
674     9808               2         978    977       kkk      Fair     4   
675     5994               2         848    847       aaa      Good    10   
676     5938               1         944    943       jjj  Like New    12   
677     3754               0        1233   1233       jjj      Fair     3   
678     4014               2         921    921       jjj      Fair     6   
679     8366               3        1385   1383       ggg      Fair     6   
680     4419               3        1170   1169       jjj      Fair    25   
681     4534               4        1043   1042       ggg  Like New     4   
682     3980               4         661    660       ccc      Good     9   
683     5401               3        1472   1470       jjj      Good    22   
684     9759               4        1035   1034       jjj      Good     2   
685     7972               2        1045   1044       hhh  Like New     8   
686     3679               1        1139   1136       hhh      Good    13   
687     5673               4         950    948       bbb      Fair     7   
688     7453               2        1021   1020       ccc  Like New     2   
689     8667               1        1651   1651       jjj      Good    22   
6

In [99]:
# item_tag_hash
lb_item_hash_labels = LabelBinarizer()
lb_results_item_hash_labels = lb_item_hash_labels.fit_transform(data["item_tag_hash"])
item_hash_labels = pd.DataFrame(lb_results_item_hash_labels, columns=lb_item_hash_labels.classes_)
data = pd.merge(data, item_hash_labels, left_index=True, right_index=True)
data.head(n=10)

In [100]:
#condition
lb_condition = LabelBinarizer()
lb_results_condition = lb_condition.fit_transform(data["condition"])
condition_labels = pd.DataFrame(lb_results_condition, columns=lb_condition.classes_)
data = pd.merge(data, condition_labels, left_index=True, right_index=True)
data.head(n=10)

In [101]:
#area_name
lb_area_name = LabelBinarizer()
lb_results_area_name = lb_area_name.fit_transform(data["area_name"])
area_name_labels = pd.DataFrame(lb_results_area_name, columns=lb_area_name.classes_)
data = pd.merge(data, area_name_labels, left_index=True, right_index=True)
data.head(n=10)

item_id  category_class  sold_price  price area_name condition  size  \
0     7966               0        1164   1162       fff      Fair     7   
1     1850               0        1005   1004       fff      Fair     3   
2     7582               2         944    944       aaa      Fair     5   
3     6560               0        1068   1067       fff      Fair     7   
4     7368               3        1407   1407       ddd      Good    15   

                  listing_at                             item_tag_hash  month  \
0 2017-02-01 16:11:18.978516  3ca192bd7558780793444f73366c58d60c9d7775      2   
1 2017-02-02 14:42:51.693295  fbaacb960902382e4f6c96f2d8f225c24eecadb4      2   
2 2017-02-03 01:55:53.406374  785a7925363bf133a7c5413c563f331c5e02cc69      2   
3 2017-01-30 23:34:02.268603  f8997252c6e5ae3d950b736e1a81160a2e937a7f      1   
4 2017-02-03 13:38:37.845010  ca59bcd3da4daac52f3fcfdc0ab963f65cf421bc      2   

   ...  aaa  bbb  ccc  ddd  eee  fff  ggg  hhh  jjj  kkk  
0  ...    0    0    0    0    0    1    0    0    0    0  
1  ...    0    0    0    0    0    1    0    0    0    0  
2  ...    1    0    0    0    0    0    0    0    0    0  
3  ...    0    0    0    0    0    1    0    0    0    0  
4  ...    0    0    0    1    0    0    0    0    0    0  

[5 rows x 216 columns]

In [102]:
# looking at individual datetypes
data.dtypes

item_id                                              int64
category_class                                       int64
sold_price                                           int64
price                                                int64
area_name                                           object
condition                                           object
size                                                 int64
listing_at                                  datetime64[ns]
item_tag_hash                                       object
month                                                int64
year                                                 int64
day                                                  int64
minute                                               int64
hour                                                 int64
weekday                                              int64
00e263ff6806064c016a643c6587b0d607a6a42d             int64
00fd4b4549a1094aae926ef62e9dbd3cdcc2e456             int

In [103]:
# print(data['size'].describe())
# print(data['size'].value_counts())

In [104]:
# data.category_class.value_counts()

In [105]:
# data.area_name.value_counts()

In [106]:
# data.sold_price.value_counts()

In [107]:
# data.condition.value_counts()

In [108]:
# data.price.value_counts()

In [109]:
# data.item_tag_hash.value_counts()

In [110]:
# data

In [111]:
data.corr()

item_id  category_class  \
item_id                                   1.000000        0.007376   
category_class                            0.007376        1.000000   
sold_price                               -0.001447        0.003725   
price                                     0.018117        0.045501   
size                                     -0.016210        0.156726   
month                                     0.047450       -0.073639   
year                                           NaN             NaN   
day                                      -0.051034        0.074634   
minute                                    0.025038       -0.070288   
hour                                      0.076547       -0.025043   
weekday                                   0.016221        0.012682   
00e263ff6806064c016a643c6587b0d607a6a42d -0.064056       -0.041737   
00fd4b4549a1094aae926ef62e9dbd3cdcc2e456 -0.000132       -0.072395   
0104cf3b45056589309effd4d0889e430018b490  0.007302        0.031318   
0200320ae3bc247e747ef93e3259bc29ddf53392  0.020489        0.059180   
0284938375fd54f17c4331b8ef9f686bfbda02c3  0.033091       -0.059068   
02ef6a4d5e9b6440ee4513baf40746cb8e872fe4 -0.007271        0.006335   
02f84308fab673d8332e1ab780a8ade20987e925  0.015785       -0.013886   
0477d720adf7c715b04850723531a5fb1bc5334b  0.046348       -0.041737   
04b69e5006d308a60f286c6d87138324d3c745c6 -0.030899       -0.110904   
05fa2de99c48086b28d6e7a491a75f6f313af79d -0.030709        0.024224   
070dafcb55881e67b7fce04cfb94faa33639b865 -0.000207       -0.059068   
071819749594ed380380dca6aed0f24e25cc9269  0.088510        0.024224   
07f97cc68eebf81afcd32f6fc0aad7e1f17e0c00  0.009470        0.031318   
081be7c370bf9e7b4c6e696276c1b2d57623b26b -0.008339       -0.027832   
0aec17ce3bff113e1c7c16e9d9dcaf90bf590974 -0.041673        0.072533   
0cf950b5e4d2ebd7c978c76091ddce6176845697  0.041739        0.024224   
0f23eb04fa3d66bce3cb03de0629ac1b4fd32bbb  0.008381        0.083814   
0fb0a8a62cbe899f9c109e5ccf6d5f3b35e33f38 -0.035688       -0.027832   
128351137a9c47206c4507dcf2e6fbeeca3a9079 -0.030176       -0.041737   
...                                            ...             ...   
e41c8fd8d6da74a91fc96008280baea77725b5a7  0.003169       -0.027832   
e6ba73dc9533e190c71bfc3877414870457f1533 -0.059296       -0.093596   
e83f7664870c1105727dd99353d0bfa01b2450b5 -0.047141       -0.059068   
e9a20a4af61c91b0232679bc583058b278fb2926  0.005778        0.078888   
ea10e810f96fca6858e37fda9832ace147eed87c -0.008072       -0.041737   
ec883370694191262ca4364fb7b34135e11947b8 -0.014135       -0.041737   
ec99f53e14fdfe8dbd7ffc6455a4b4cf46e5c609 -0.037518        0.027991   
eeb8f1dbcd3eedab645d5ab893d199d494579bf3  0.026703       -0.039473   
ef9cb1abfdb1d45bb08bd2742f179591c8266187 -0.017286       -0.059068   
f0a3865870d476fd2019497ce810af59b1f3581b -0.029841       -0.029577   
f673929b7ae05128dd473c556386a7b585483947 -0.050771       -0.072395   
f69e508a40c73a21d4d2b63aaa03339fe7dbd165  0.051520       -0.013886   
f8997252c6e5ae3d950b736e1a81160a2e937a7f  0.001333       -0.123978   
fbaacb960902382e4f6c96f2d8f225c24eecadb4 -0.011097       -0.093596   
fdc01209f90eda589f0453b7e29e0114923ecd8b  0.005533        0.039700   
fee8346a5a401a9c314846811346613d2ddf998c  0.034569        0.098597   
ff33a8f10515011cba0d191ae58f7f9a4dd7a3e1 -0.007790       -0.069699   
Fair                                     -0.085072       -0.060626   
Good                                      0.021409        0.054792   
Like New                                  0.063196        0.002984   
aaa                                      -0.058524        0.025537   
bbb                                      -0.023803       -0.006759   
ccc                                       0.021431       -0.063878   
ddd                                       0.003935       -0.003060   
eee                                      -0.015116        0.045642   
fff                                       0.027848   

In [112]:
# data.columns

In [113]:
independent_variables = data.columns.tolist()
independent_variables.remove('category_class')
independent_variables.remove('listing_at')
independent_variables.remove('year')
independent_variables.remove('item_tag_hash')
independent_variables.remove('condition')
independent_variables.remove('area_name')
dependent_variable = ['category_class']

features = data[independent_variables]
label = data[dependent_variable]

In [114]:
features

item_id  sold_price  price  size  month  day  minute  hour  weekday  \
0       7966        1164   1162     7      2    1      11    16        2   
1       1850        1005   1004     3      2    2      42    14        3   
2       7582         944    944     5      2    3      55     1        4   
3       6560        1068   1067     7      1   30      34    23        0   
4       7368        1407   1407    15      2    3      38    13        4   
5       9404         980    979     3      1   30      33    19        0   
6       8367        1371   2102    11      2    1      54    14        2   
7       7710         771    770     2      2    3      16    14        4   
8       5402        1004   1003     2      1   31      56    15        1   
9       1909        1096   1095     3      2    1      31    14        2   
10      2791         971    970     4      1   29      39    21        6   
11      7451        1160   1157     3      1   31       8     4        1   
12      6184        1332   1329    26      1   30      50    14        0   
13      2327        1077   1077     6      1   31      29     7        1   
14      4990        1094   1091     7      1   29      13    22        6   
15      8635         889    888     7      1   30      51     2        0   
16      3273        1154   1151     9      2    1       9     1        2   
17      6054         877    877     4      1   31      46    20        1   
18      8212        1188   1186    14      1   31       6    17        1   
19      9175         858    856     7      1   29      41     3        6   
20      6034        1159   1157    14      1   29       5    22        6   
21      5531        1424   1423     9      2    3      11     3        4   
22      3987        1187   1187    13      1   31      42    21        1   
23      2193         876    876     2      2    2      59    13        3   
24      5804        1058   1056    10      2    2      31    20        3   
25      4562        1221   1220    12      2    2      14    14        3   
26      2966         933    930     5      1   30      49    17        0   
27      3084        1046   1046     3      1   31      49    19        1   
28      6428        1062   1062    18      2    1      47     0        2   
29      7388        1101   1102     3      2    1       3     5        2   
..       ...         ...    ...   ...    ...  ...     ...   ...      ...   
670     6604         870    868     4      1   31      36    16        1   
671     9262        1272   1271    20      2    3      54     2        4   
672     1587        1267   1267    31      2    2      27     0        3   
673     4718         974    974     3      2    2      56    14        3   
674     9808         978    977     4      1   29       2    13        6   
675     5994         848    847    10      1   31      45     2        1   
676     5938         944    943    12      1   31      36     0        1   
677     3754        1233   1233     3      1   30      45    17        0   
678     4014         921    921     6      1   30      10     2        0   
679     8366        1385   1383     6      2    3      55     3        4   
680     4419        1170   1169    25      2    2      46     2        3   
681     4534        1043   1042     4      2    2      49     7        3   
682     3980         661    660     9      1   30       8    20        0   
683     5401        1472   1470    22      2    2      44    17        3   
684     9759        1035   1034     2      2    1      30    17        2   
685     7972        1045   1044     8      1   31      17     7        1   
686     3679        1139   1136    13      2    2      10     9        3   
687     5673         950    948     7      1   31      18    12        1   
688     7453        1021   1020     2      2    1      58     1        2   
689     8667        1651   1651    22      2    1      19     9        2   
690     3626        1039   1039    25      1   31    

In [115]:
label

category_class
0                 0
1                 0
2                 2
3                 0
4                 3
5                 2
6                 1
7                 2
8                 0
9                 4
10                4
11                0
12                1
13                2
14                0
15                0
16                1
17                0
18                2
19                2
20                0
21                3
22                0
23                0
24                2
25                0
26                2
27                0
28                0
29                0
..              ...
670               4
671               3
672               3
673               0
674               2
675               2
676               1
677               0
678               2
679               3
680               3
681               4
682               4
683               3
684               4
685               2
686               1
687               4
688               2
689               1
690               0
691               2
692               3
693               4
694               0
695               0
696               0
697               1
698               1
699               3

[700 rows x 1 columns]

In [116]:
# Splitting the data using Sklearn Model Selection, this should give us better results for cross valication
X_train,X_test,Y_train,Y_test = train_test_split(features, label, test_size=0.33, random_state=1)

## Multinomial Naive Bayes

In [117]:
# Naive Bayes
alpha = [3, 1, 0.3, 0.1, 0.03, 0.01, 0.003]
f1_scorer = make_scorer(f1_score, average='macro')
for i in alpha:
    naive_bayes = MultinomialNB(alpha = i)
    print(cross_val_score(naive_bayes,X_train,Y_train.values.ravel(),cv=3,scoring=f1_scorer))
    

[0.18692297 0.23966327 0.18889308]
[0.16538223 0.24974135 0.186226  ]
[0.18395983 0.27906297 0.19903367]
[0.19021079 0.27906297 0.20594859]
[0.19034701 0.31025061 0.21517242]
[0.19568034 0.31527148 0.21540777]
[0.19568034 0.32482142 0.22366414]


In [118]:
naive_bayes = MultinomialNB(alpha = 0.01)
naive_bayes = naive_bayes.fit(X_train,Y_train.values.ravel())
Y_predicted_naive_bayes = naive_bayes.predict(X_test)

# F1 Score, Precision, Recall
Precision, Recall, F1score, Support = prfs(Y_test, Y_predicted_naive_bayes, average='macro', beta=1.0)
print("Values for Naive Bayes : ","Precision ->",Precision," Recall->",Recall," F1score->",F1score)

Values for Naive Bayes :  Precision -> 0.40796195462317575  Recall-> 0.427088551753345  F1score-> 0.3450244083213879


## Logistic Regression

In [124]:
max_iter = [10000, 100000, 1000000, 10000000]
for i in max_iter:
    linear_regression = LogisticRegression(
                                        penalty='l2', 
                                        tol=0.0001, 
                                        C=1, 
    #                                     class_weight="balanced", 
                                        solver='lbfgs', 
                                        max_iter=i, 
                                        multi_class='multinomial',
                                        n_jobs=2,
                                        verbose=1)
    print(cross_val_score(linear_regression,X_train,Y_train.values.ravel(),cv=3,scoring=f1_scorer))

[Parallel(n_jobs=2)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done   1 out of   1 | elapsed:    6.7s finished
[Parallel(n_jobs=2)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done   1 out of   1 | elapsed:    6.1s finished
[Parallel(n_jobs=2)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done   1 out of   1 | elapsed:    5.5s finished
[Parallel(n_jobs=2)]: Using backend LokyBackend with 2 concurrent workers.


[0.55806869 0.547639   0.58345937]


[Parallel(n_jobs=2)]: Done   1 out of   1 | elapsed:    7.7s finished
[Parallel(n_jobs=2)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done   1 out of   1 | elapsed:    7.6s finished
[Parallel(n_jobs=2)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done   1 out of   1 | elapsed:    7.7s finished
[Parallel(n_jobs=2)]: Using backend LokyBackend with 2 concurrent workers.


[0.62450397 0.59006315 0.62985865]


[Parallel(n_jobs=2)]: Done   1 out of   1 | elapsed:    7.8s finished
[Parallel(n_jobs=2)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done   1 out of   1 | elapsed:    7.7s finished
[Parallel(n_jobs=2)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done   1 out of   1 | elapsed:    7.6s finished
[Parallel(n_jobs=2)]: Using backend LokyBackend with 2 concurrent workers.


[0.62450397 0.59006315 0.62985865]


[Parallel(n_jobs=2)]: Done   1 out of   1 | elapsed:    7.9s finished
[Parallel(n_jobs=2)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done   1 out of   1 | elapsed:    7.7s finished
[Parallel(n_jobs=2)]: Using backend LokyBackend with 2 concurrent workers.


[0.62450397 0.59006315 0.62985865]


[Parallel(n_jobs=2)]: Done   1 out of   1 | elapsed:    7.6s finished


In [127]:
linear_regression = LogisticRegression(
                                        penalty='l2', 
                                        tol=0.0001, 
                                        C=1, 
                                        solver='lbfgs', 
                                        max_iter=100000, 
                                        multi_class='multinomial',
                                        n_jobs=2,
                                        verbose=1)
linear_regression = linear_regression.fit(X_train,Y_train.values.ravel())
Y_predicted_linear_regression = linear_regression.predict(X_test)

# F1 Score, Precision, Recall
Precision, Recall, F1score, Support = prfs(Y_test, Y_predicted_linear_regression, average='macro', beta=1.0)
print("Values for Logistic Regression : ","Precision ->",Precision," Recall->",Recall," F1score->",F1score)

[Parallel(n_jobs=2)]: Using backend LokyBackend with 2 concurrent workers.


Values for Logistic Regression :  Precision -> 0.7183712121212121  Recall-> 0.6446269427080347  F1score-> 0.6663927628386265


[Parallel(n_jobs=2)]: Done   1 out of   1 | elapsed:    9.8s finished


## Random Forset

In [140]:
random_forest = RandomForestClassifier(n_estimators=1000, 
                                       criterion='gini',
                                       n_jobs=2,
#                                        class_weight="balanced",
                                       verbose=1)
print(cross_val_score(random_forest, X_train, Y_train.values.ravel(), cv=3, scoring=f1_scorer))

[Parallel(n_jobs=2)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done 1000 out of 1000 | elapsed:    0.8s finished
[Parallel(n_jobs=2)]: Using backend ThreadingBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done  46 tasks      | elapsed:    0.0s
[Parallel(n_jobs=2)]: Done 196 tasks      | elapsed:    0.0s
[Parallel(n_jobs=2)]: Done 446 tasks      | elapsed:    0.1s
[Parallel(n_jobs=2)]: Done 796 tasks      | elapsed:    0.1s
[Parallel(n_jobs=2)]: Done 1000 out of 1000 | elapsed:    0.2s finished
[Parallel(n_jobs=2)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done 1000 out of 1000 | elapsed:    0.6s finished
[Parallel(n_jobs=2)]: Using backend ThreadingBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done  46 tasks      | elapsed:    0.0s
[Parallel(n_jobs=2)]: Done 196 tasks      | elapsed:    0.0s
[Parallel(n_jobs=2)]: Done 446 tasks      | elapsed:    0.1s
[Parallel(n_jobs=2)]: Done 796 tasks      | ela

[0.61664891 0.6149503  0.57120203]


In [143]:
random_forest = RandomForestClassifier(n_estimators=1000, 
                                       criterion='gini',
                                       n_jobs=2,
#                                        class_weight="balanced",
                                       verbose=1)
random_forest = random_forest.fit(X_train,Y_train.values.ravel())
Y_predicted_random_forest = random_forest.predict(X_test)

# F1 Score, Precision, Recall
Precision, Recall, F1score, Support = prfs(Y_test, Y_predicted_random_forest, average='macro', beta=1.0)
print("Values for random_forest : ","Precision ->",Precision," Recall->",Recall," F1score->",F1score)

[Parallel(n_jobs=2)]: Using backend ThreadingBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done  46 tasks      | elapsed:    0.0s
[Parallel(n_jobs=2)]: Done 196 tasks      | elapsed:    0.1s
[Parallel(n_jobs=2)]: Done 446 tasks      | elapsed:    0.3s
[Parallel(n_jobs=2)]: Done 796 tasks      | elapsed:    0.6s
[Parallel(n_jobs=2)]: Done 1000 out of 1000 | elapsed:    0.7s finished
[Parallel(n_jobs=2)]: Using backend ThreadingBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done  46 tasks      | elapsed:    0.0s
[Parallel(n_jobs=2)]: Done 196 tasks      | elapsed:    0.1s
[Parallel(n_jobs=2)]: Done 446 tasks      | elapsed:    0.1s
[Parallel(n_jobs=2)]: Done 796 tasks      | elapsed:    0.2s


Values for random_forest :  Precision -> 0.6767219067995767  Recall-> 0.591782284355548  F1score-> 0.612128218602207


[Parallel(n_jobs=2)]: Done 1000 out of 1000 | elapsed:    0.2s finished


## Decision Tree

In [146]:
decision_tree = DecisionTreeClassifier(class_weight="balanced", 
                                    presort=True)
print(cross_val_score(decision_tree, X_train, Y_train.values.ravel(), cv=3, scoring=f1_scorer))

[0.45461245 0.45166978 0.43912389]


In [148]:
decision_tree = decision_tree.fit(X_train,Y_train.values.ravel())
Y_predicted_decision_tree = decision_tree.predict(X_test)

# F1 Score, Precision, Recall
Precision, Recall, F1score, Support = prfs(Y_test, Y_predicted_decision_tree, average='macro', beta=1.0)
print("Values for decision_tree : ","Precision ->",Precision," Recall->",Recall," F1score->",F1score)

Values for decision_tree :  Precision -> 0.5463882388398397  Recall-> 0.5464328285123147  F1score-> 0.5448302011716384
