In [1]:
import numpy as np 
import pandas as pd

In [2]:
np.__version__


'1.15.4'

In [3]:
pd.__version__

'0.24.0'

In [4]:
l = list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
np.zeros(10,dtype="int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
np.ones((3,6),dtype=float)

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [7]:
np.full((2,2), 2.134)

array([[2.134, 2.134],
       [2.134, 2.134]])

In [8]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [11]:
# help(np.random.binomial)

In [14]:
np.random.binomial(2,0.5,10)

array([1, 1, 1, 0, 1, 1, 1, 2, 0, 0])

In [16]:
np.random.normal(0, 0.5, (2,2))

array([[ 0.21813681, -0.63472833],
       [-0.021881  , -0.26892315]])

In [18]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [19]:
np.random.seed(0)

In [20]:
x1 = np.random.randint(10, size=5)

In [22]:
x1

array([5, 0, 3, 3, 7])

In [23]:
# help(np.random.randint)

In [24]:
x2 = np.random.normal(0, 1, (3,4))
x2

array([[ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351],
       [ 0.76103773,  0.12167502,  0.44386323,  0.33367433]])

In [25]:
print(x2.size, x2.shape, x2.ndim)

12 (3, 4) 2


In [26]:
x2[0][0]

1.8675579901499675

In [27]:
x2[-1]

array([0.76103773, 0.12167502, 0.44386323, 0.33367433])

In [28]:
x2[0][0] = 0
x2

array([[ 0.        , -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351],
       [ 0.76103773,  0.12167502,  0.44386323,  0.33367433]])

In [29]:
x1[2::]

array([3, 3, 7])

In [40]:
x = np.random.randint(15, size=(2,5))
y = np.random.randint(15, size=(2,5))
print(x)
print(y)

[[ 9  3  6  7 11]
 [14  2 11  0 14]]
[[ 3  5 12  9 10]
 [ 4 11  4  6  4]]


In [33]:
np.concatenate([x,y], axis=1)

array([[ 2,  3,  8,  1,  3,  0,  1,  9,  9,  0],
       [13,  3,  3, 14,  7, 10,  4,  7,  3, 14]])

In [34]:
np.concatenate([[x,y], [y,x]], axis= 2)

array([[[ 2,  3,  8,  1,  3,  0,  1,  9,  9,  0],
        [13,  3,  3, 14,  7, 10,  4,  7,  3, 14]],

       [[ 0,  1,  9,  9,  0,  2,  3,  8,  1,  3],
        [10,  4,  7,  3, 14, 13,  3,  3, 14,  7]]])

In [35]:
z = np.random.randint(10, size=(2, 1))
z, x

(array([[2],
        [7]]), array([[ 2,  3,  8,  1,  3],
        [13,  3,  3, 14,  7]]))

In [38]:
np.hstack([x,z])

array([[ 2,  3,  8,  1,  3,  2],
       [13,  3,  3, 14,  7,  7]])